[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = "pangloss/vim-javascript"

[[plugins]]
repo = "mxw/vim-jsx"

[[plugins]]
repo = 'JulesWang/css.vim'

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/nerdtree.git'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'burnettk/vim-angular'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'Shougo/vimproc.vim'
